service tests, h2 tests, mvc
saadow/jaw-dropping-customers pull request #2
Opened 2019-03-21 12:12 UTC by saadow

2019-03-25 10:16 UTC, SerhiiPasko requested changes
Read comments

2019-03-25 10:16 UTC, SergeyPasko commented on src/main/java/service/CustomerServiceImpl.java
> -	@Override
This is bad. @Override must present

2019-03-25 10:16 UTC, SergeyPasko commented on src/test/java/repository/CustomerRepositoryIntegrationTest.java
> +public class CustomerRepositoryIntegrationTest {
I wrote this type of test only as example

2019-03-25 10:16 UTC, SergeyPasko commented on src/test/resources/scripts/schema.sql
> +CREATE SEQUENCE IF NOT EXISTS CUSTOMER_SEQ
Haven't sence. You didn't need that, becouse you havent Id generator in Customer entity

2019-03-25 12:41 UTC, Artsapollo commented
Now looks good

2019-03-25 12:42 UTC, Artsapollo approved these changes
Now looks good

2019-03-26 08:49 UTC, SerhiiPasko approved these changes
Good

2019-03-26 15:58 UTC, merged